### ISSUE TITLE
How to set host and open in browser?

### ISSUE THREAD

**Issue by n1kko777** [texm/shokku#11]
I cant find any tutorial how to open it in browser. Set domain, set port but it doesnt work

**Comment by texm** [comment]
Hi, there could be a number of reasons for this - one thing to try is seeing if other simpler Dokku apps work.
Try following the [Dokku "getting started"](https://dokku.com/docs/deployment/application-deployment/) guide, and see if that is accessible from your browser.

Otherwise I would need to know more about your setup to troubleshoot any issues

**Comment by n1kko777** [comment]
After fully uninstall i got it! Thanks =)
