### ISSUE TITLE
Wondering why Shokku is installed in a container and not as a separate executable?

### ISSUE THREAD

**Issue by Gys** [texm/shokku#12]
I was just wondering what the design decisions were behind it. Why is the the Shokku executable installed in a container using Dokku, instead of installed as a separate executable?

**Comment by texm** [comment]
Hi

- In a nutshell, the container image is a convenience for me:
  - It simplifies documentation & deployment, since I only need to consider one method. Dokku provides good support for running containers, so we can piggyback on that
  - The repo can easily be cloned and built as an executable if needed by users. The issue for me is providing & troubleshooting builds for all systems/architectures. 
- Shokku does not necessarily need to be installed using Dokku, you could achieve the same results using whatever orchestrator/init system you choose. However since it is an application built for Dokku, we can assume there is a Dokku installation to deploy it to (and get all the Dokku niceties of UX/SSL/plugins/monitoring).
