### ISSUE TITLE
Caddy?

### ISSUE THREAD

**Issue by marcoantonio123456** [texm/shokku#14]
is it possible to deploy through Caddy?

**Comment by texm** [comment]
To clarify - do you mean accessing Shokku itself via Caddy as a reverse proxy instead of the Dokku-configured proxy, or Shokku deploying apps using the [Dokku Caddy Proxy](https://dokku.com/docs/networking/proxies/caddy/)?

The former would be fairly easy to accomplish assuming you have shokku running on a host, using docker or as a standalone binary. 

The latter would require some code to add a setting for the proxy dokku uses, on the backend:
```go
e.Dokku.SetAppProxyType("--global", dokku.ProxyTypeCaddy)
```
(assuming `ProxyTypeCaddy` is added in my underlying `dokku-go` library [here](https://github.com/texm/dokku-go/blob/main/proxy.go#L67))

**Comment by marcoantonio123456** [comment]
I just needed to point a port towards the app. Thank you for the also helpful comment @texm
